# Nome do projeto a ser definido para setar todos os argumentos necessarios "preferenciamente sempre o nome do diretório do projeto para que o alias que criei funcione"
name: curso-mvc

services:
  app:
    # O build especifíca o caminho para o Dockerfile a ser utilizado, como o mesmo está na raiz é usado o `.`
    container_name: $COMPOSE_PROJECT_NAME-dev-php-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: "8.3.20-fpm-alpine3.20"
        PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
        # Obtém automaticamente o nome do projeto a partir da variável padrão linux
        USER_NAME: "${USER:-www-data}"
    ports:
      - 8080:8080
      - 443:443 # https
    volumes:
      # Bind mount - que conecta o diretório atual ao contêiner da aplicação
      - ./:/var/www/${COMPOSE_PROJECT_NAME}
      # Volume para persistir o vendor do container sem ser sobrescrito pelo host
      - vendor_data:/var/www/${COMPOSE_PROJECT_NAME}/vendor

volumes:
  # Volume nomeado para armazenar o conteúdo do vendor
  vendor_data:
