name: curso-mvc

services:
  app:
    container_name: $COMPOSE_PROJECT_NAME-dev-php-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: "8.3.20-fpm-alpine3.20"
        PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
        USER_NAME: "${USER:-www-data}"
    ports:
      - 8080:8080
      - 443:443 # https
    volumes:
      - ./:/var/www/${COMPOSE_PROJECT_NAME}
      - vendor_data:/var/www/${COMPOSE_PROJECT_NAME}/vendor

volumes:
  vendor_data:
